### PR TITLE
SDP-1 refactor: fit to OOP

### PR DESCRIPTION
**Pull request by logpacket**
Refactor fit to OOP.

### Changes:
- Change `GameSettings` and `GameState` to record class.
- Delete abused `static` keywords
- Correct methods/variables/constants name by this [convention](https://discord.com/channels/1288030976210898964/1288030976210898973/1301751651723382856)
- Change complex methods to simple

### CODE REVIEW

**Review by mhojune — APPROVED** [review]
Thank you for your hard work^^

**Review by mjwoon — APPROVED** [review]
LGTM

**Comment by dobi02** [comment]
LGTM

**Review by dobi02 — COMMENTED** [review]
LGTM

**Review by dobi02 — APPROVED** [review]
LGTM

**Review by yhjong — APPROVED** [review]
LGTM

**Comment by jiwoninnuk** [comment]
LGTM

**Pull request merged**
